- name: Ignore demo
  hosts: localhost
  tasks:
    - name: Run shell command
      ansible.builtin.shell: exit1
      ignore_errors: yes

    - name: Say Hi
      ansible.builtin.debug:
        msg: Yo Its alright!