- name: Ignore demo
  hosts: localhost
  tasks:
    - name: Rescue
      block:
        - name: Run shell command
          ansible.builtin.shell: exit 1

      rescue:
        - name: Say Hi
          ansible.builtin.debug:
            msg: Hello Man